### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'shape'

### ISSUE THREAD

**Issue by Dhruv2012** [sainimohit23/FaceNet-with-TripletLoss#3]
This error is shown in model.fit_generator() function line.I have made my custom generator.But there is no issue in that as the code runs on other model .Did u face any such problem?
Thank you.....

**Comment by sainimohit23** [comment]
Hi @Dhruv2012 ,

I have made some changes to code. Download it and try to run it again.

**Comment by Dhruv2012** [comment]
Hi, @sainimohit23, what was the change that u made. Was it in the generator function (yield part returning the label as well). I returned a random label y  in the generator function as we don't need the label in triplet loss training and the error got solved.Am I Right?
But the model after training at certain epochs does not perform well. i don't know what is the issue? Hope u can help...

**Comment by Dhruv2012** [comment]
> Hi, @sainimohit23, what was the change that u made. Was it in the generator function (yield part returning the label as well). I returned a random label y in the generator function as we don't need the label in triplet loss training and the error got solved.Am I Right?
> But the model after training at certain epochs does not perform well. i don't know what is the issue? Hope u can help...

The label Y returned was a random label in the geneartor function.

**Comment by sainimohit23** [comment]
@Dhruv2012 I have changed the implementation of triplet loss and generator function. I have also made some changes in MTCNN and other files so that we don't have to make dictionaries manually. And yes you are right, we don't need the label Y. It is there so that keras don't throw any exception/error.

For the performance, I have not tuned hyperparameters at all. I don't have a GPU to test the performance of model extensively. I have just tried to implement the concepts that I have learned in deeplearning.ai's course.Also I don't have any labelled data to find optimal threshold using [ROC](https://en.wikipedia.org/wiki/Receiver_operating_characteristic) . I have made this repository because I couldn't find much implementations of triplet loss and it was a great learning process for me.
